// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiCursoAngular.DataBase;

#nullable disable

namespace apiCursoAngular.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("apiCursoAngular.EntityModels.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("imagen");

                    b.Property<string>("Nombre")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Precio")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.ToTable("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
